# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: sumi
google_analytics: sumi
title: sumi

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: sumi

description: Stylish Jekyll Theme
author:
  name: sumi
  email: selina2000@naver.com
  github: sumi-0011
  twitter: sumi
  pinterest: selina20000208
  linkedin: sumi0011
  bio: Hi!
  email_md5: selina2000@naver.com

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
